cachelib/allocator/CacheItem.h: use __atomic_compare_exchange_n in place of __sync_bool_compare_and_swap for unaligned input (expiryTime_ is not 4-byte-aligned; member of a packed class)
Summary:
This avoids the following errors:

  cachelib/allocator/CacheItem.h:924:9: error: __sync builtin operation MUST have natural alignment (consider using __atomic). [-Werror,-Wsync-alignment]
    924 |     if (__sync_bool_compare_and_swap(&expiryTime_, currExpTime,

Since this is a packed class, any preceding member whose size is not a multiple of 4 will cause this problem.

Reviewed By: dmm-fb

Differential Revision: D57364470

fbshipit-source-id: fb823b6416c289aabd47b76baeb9819f5c3ecc50