remove 'noexcept' from ChainedHashTable's ctor
Summary:
Diff D29706284 (https://github.com/facebookincubator/CacheLib/commit/0d8928e534d69d28e68bfea17b813ba00113b9f8) added back the 'noexcept' on ChainedHashTable's
constructor (assuming the related LLVM bug has been resolved).
However, it reintroduced a compilation error when building with GCC
as open-source project: GCC fails with:
   "config() is implicitly deleted because its exception-specification does
    not match the implicit exception-specification <noexcept (false)>"
followed by:
   "CacheAllocatorConfig.h:522:29: error: use of deleted function
    constexpr facebook::cachelib::ChainedHashTable::Config::Config()

This patch removes (again) the 'noexcept' keyword.

As a side note, the previous comment when 'noexcept' was first removed was:
  // TODO(sugak) this is changed to unblock the LLVM upgrade$
  // The fix is not completely understood, but it's a safe change$
  // T16521551$
  // - Config() noexcept = default;$

Reviewed By: therealgymmy

Differential Revision: D29919114

fbshipit-source-id: 17dd5b9021415ca5f768b6dc4d53800daabf6d0b