cachelib/compact_cache/CCacheFixedLruBucket.h: mark non-POD "val" member as packed
Summary:
This avoids the following errors:

  cachelib/compact_cache/CCacheFixedLruBucket.h:54:11: error: not packing field 'val' as it is non-POD for the purposes of layout [-Werror,-Wpacked-non-pod]
  cachelib/compact_cache/CCacheFixedLruBucket.h:63:17: error: static assertion failed due to requirement 'sizeof(facebook::cachelib::FixedLruBucket<facebook::cachelib::CompactCacheDescriptor<facebook::tao::AssocCompactCacheKey<facebook::tao::AssocFbidKey>, facebook::cachelib::ValueDescriptor<facebook::tao::CountVersion>>, 8>::Entry) == sizeof(facebook::tao::AssocCompactCacheKey<facebook::tao::AssocFbidKey>) + sizeof(facebook::tao::CountVersion)': Entry packing went awry
  cachelib/compact_cache/CCacheFixedLruBucket.h:63:17: error: static assertion failed due to requirement 'sizeof(facebook::cachelib::FixedLruBucket<facebook::cachelib::CompactCacheDescriptor<facebook::tao::AssocCompactCacheKey<facebook::tao::HashKey>, facebook::cachelib::ValueDescriptor<facebook::tao::CountVersion>>, 8>::Entry) == sizeof(facebook::tao::AssocCompactCacheKey<facebook::tao::HashKey>) + sizeof(facebook::tao::CountVersion)': Entry packing went awry

As of llvm16, applying the "packed" attribute to a struct/class with a non-POD member does **not** pack that member.
Applying the attribute also to each such non-POD member restores the previous behavior.

Reviewed By: bunnypak

Differential Revision: D57521794

fbshipit-source-id: ee70f949bc40e8e285cc57eaed723be8a01e6d5a