cachelib/datatype/Map.h: mark non-POD "second" member as packed
Summary:
This avoids the following errors:

  cachelib/datatype/Map.h:350:16: error: not packing field 'second' as it is non-POD for the purposes of layout [-Werror,-Wpacked-non-pod]

As of llvm16, applying the "packed" attribute to a struct/class with a non-POD member does not pack that member.
Applying the attribute also to each such non-POD member restores the previous behavior.

Reviewed By: therealgymmy

Differential Revision: D57814499

fbshipit-source-id: b917ef00f01a165b40af3657007e242e469ff0fa