cachelib/compact_cache/CCacheFixedLruBucket.h: mark non-POD "key" member as packed
Summary:
This avoids the following errors:

  cachelib/compact_cache/CCacheFixedLruBucket.h:52:9: error: not packing field 'key' as it is non-POD for the purposes of layout [-Werror,-Wpacked-non-pod]

As of llvm16, applying the "packed" attribute to a struct/class with a non-POD member does not pack that member.
Applying the attribute also to each such non-POD member restores the previous behavior.

Reviewed By: therealgymmy

Differential Revision: D57814496

fbshipit-source-id: 4dcc17e74ebe0b024e953bdf0ac9a1aadfd56c28