updating libbpf version to latest
Summary:
In D77978567 `oss-katran-linux-getdeps`  (https://www.internalfb.com/sandcastle/job/36028799188271308?no_redirect=1) fails due:

```
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/katran/katran/lib/BaseBpfAdapter.cpp:244:10: error: ‘struct bpf_map_create_opts’ has no member named ‘token_fd’
  244 |     opts.token_fd = bpfTokenFd_;
      |          ^~~~~~~~
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/katran/katran/lib/BaseBpfAdapter.cpp:245:23: error: ‘BPF_F_TOKEN_FD’ was not declared in this scope
  245 |     opts.map_flags |= BPF_F_TOKEN_FD;
      |                       ^~~~~~~~~~~~~~
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/katran/katran/lib/BaseBpfAdapter.cpp: In member function ‘int katran::BaseBpfAdapter::setBpfTokenFromFilePath(const char*)’:
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/katran/katran/lib/BaseBpfAdapter.cpp:937:18: error: ‘bpf_token_create’ was not declared in this scope; did you mean ‘bpf_iter_create’?
  937 |   auto tokenFd = bpf_token_create(bpfFsFd, nullptr);
      |                  ^~~~~~~~~~~~~~~~
      |                  bpf_iter_create
```

looking at the logs I see it's using 0.7.0:

```
-- Checking for module 'libbpf'
--   Found libbpf, version 0.7.0
```

getdeps manifests have libbpf at 0.7.0 while the prod version is at 1.6.2. Updating to use latest version.

Checking libbpf usage in manifests: https://fburl.com/code/1whmrzqu Seems like the only user is Katran

Reviewed By: genevievehelsel

Differential Revision: D82586799

fbshipit-source-id: e2fade71ef507743d10c1c096c34b7d14180dcbf