cachelib/datatype/Map.h: remove "= default" and explicit constructor, so aggregate initialization works
Summary:
This avoid the errors:
```
error: no matching constructor for initialization of 'facebook::cachelib::detail::HashTable<unsigned long>'
    : HashTable(capacity) {
no matching constructor for initialization of 'facebook::cachelib::detail::HashTable<unsigned long>::Entry'
  Entry newE{key, addr};
```

memcache errors from migrating to platform010 P483995069
mcrouter errors from migrating to platform010 P483996489

More information on C++20 aggregate initialization: https://stackoverflow.com/questions/57271400/why-does-aggregate-initialization-not-work-anymore-since-c20-if-a-constructor

Reviewed By: stuclar

Differential Revision: D34601272

fbshipit-source-id: 96eed893fb22b551aea8408bd61295cbdcf6677d