cachelib/datatype/RangeMap.h: mark non-POD "value" member as packed
Summary:
This avoids the following errors:

  cachelib/datatype/RangeMap.h:51:16: error: not packing field 'value' as it is non-POD for the purposes of layout [-Werror,-Wpacked-non-pod]

As of llvm16, applying the "packed" attribute to a struct/class with a non-POD member does not pack that member.
Applying the attribute also to each such non-POD member restores the previous behavior.

Reviewed By: therealgymmy

Differential Revision: D57814501

fbshipit-source-id: b9485568319a8060dc326ab79dadbc4c9393c874