pacify compilers with 3 args to open(2)
Summary:
Some compilers (gcc on recent ubuntu) requires having the 3rd argument
(mode) when calling open(2) with O_CREAT.

e.g.
this will succeed:
 int fd = open("filename", O_RDWR|_CREAT, S_IRWXU);
but this will fail:
 int fd = open("filename", O_RDWR|_CREAT);
with the following error:
  /usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:24: error:
       call to '__open_missing_mode' declared with attribute error:
          open with O_CREAT or O_TMPFILE in second argument needs 3 arguments

Initial version of this patch added the 3rd 'mode' argument.

This version replaces direct calls to open(2) with Folly::File().

Reviewed By: sathyaphoenix

Differential Revision: D31742093

fbshipit-source-id: 0e413dedf411a3653224b0892954e5a258c00e43