Fix OSS build failure in CacheLib by updating to C++20 standard
Summary:
The OSS build was failing because it was using the C++17 standard. The error log showed a static assertion failure: Thrift:data/users/murtovi/scratch/dataZusersZmurtoviZfbsource/fbcode_builder_getdeps/installed/fbthrift/include/thrift/lib/cpp2/Thrift.h:34:21: error: static assertion failed: Thrift must be built with C++20 or later.
   34 |     FOLLY_CPLUSPLUS >= 202002L, "Thrift must be built with C++20 or later.");

After updating the build configuration to use the C++20 standard, the OSS build completes successfully without any issues.

Reviewed By: pbhandar2, IvanTopolcic

Differential Revision: D80132272

fbshipit-source-id: eb419d1a8c4918ba03a38778cb70b59c08b9bedd